writer_path: /home/data/workspace/events/deep_learning/ResNetAdapt-Transformer-CTC
show_step: 10
grad_clip: 1.0
inference_step: 10000
epoch: 100
device: cuda:0
max_length: &max_length 50
characters: &characters $"['blank'] + [item.strip() for item in open('vocab/radical/word_v2.txt', 'r', encoding='utf-8').readlines()] + ['end']"
radical_characters: !!python/object/apply:eval ["['blank'] + [item.strip() for item in open('vocab/radical/radical_v2.txt', 'r', encoding='utf-8').readlines()] + ['end']"]
Transforms: &transforms
  - name: LoadKeys
    args:
      keys: [ images ,text ]
  - name: Resize
    args:
      max_size: [ -1 ,32 ]
      is_pad: True
      in_key: [ images ,text ]
      out_key: [ image_pad ,images ,text ]
  - name: ZeroMeanNormal
    args:
      scale: $"1. / 255."
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224 ,0.225 ]
  - name: LabelCoder
    args:
      characters: *characters
      in_key: text
      out_key: text
  - name: LabelCTCCollate
    args:
      max_length: *max_length
      in_key: text
      out_key: [ text,lengths ]
  - name: ImageReshape
    args:
      permute_indices: [ 0 ,3 ,1 ,2 ]
  - name: KeepKeyTensor
    args:
      keep_data_keys: { images: float32 }
      keep_label_keys: { text: long, lengths: long }
Filter: &filter
  - name: LabelVocabCheckFilter
    args:
      label_length_limit: *max_length  # 一般和max_length相同或者max_length - 1
      characters: *characters
  - name: ImageCheckFilter
    args:
data:
  train:
    batch_size: 8
    shuffle: True
    num_workers: 8
    Dataset:
      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/train_ship_rec_data/2023_online_lmdb_1
          recache: False
          cache_path: chinese.npy
          filter: *filter

      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/train_ship_rec_data/2023_online_lmdb_2-0
          recache: False
          cache_path: chinese.npy
          filter: *filter
      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/train_ship_rec_data/ch_street/train
          recache: False
          cache_path: chinese.npy
          filter: *filter
      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/train_ship_rec_data/411w_train
          recache: False
          cache_path: chinese.npy
          filter: *filter
    Transforms: *transforms
  val:
    batch_size: 8
    shuffle: True
    num_workers: 8
    Dataset:
      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/valid_ship_rec_data/2023_online_lmdb_0
          recache: False
          cache_path: chinese.npy
          filter: *filter
      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/valid_ship_rec_data/lmdb
          recache: False
          cache_path: chinese.npy
          filter: *filter
      - name: LmdbDatasetFilter
        args:
          root: /home/data/data_old/lmdb/valid_ship_rec_data/ch_street/val
          recache: False
          cache_path: chinese.npy
          filter: *filter
    Transforms: *transforms
model:
  resume_path:
  save_path: /home/data/workspace/training_models/deep_learning/ResNetAdapt-Transformer-CTC
  strict: False
  Modules:
    - name: ResNetAdapt
      args:
        input_channel: 3
        output_channel: 512
    - name: Reshape
      args:
        transpose_index: [ 0 ,3 ,2 ,1 ]
        reshape_size: [ -1, -1 ,512 ]
    - name: Transformer
      args:
        width: 512
        layers: 2
        heads: 16
    - name: FCPrediction
      args:
        in_channel: 512
        n_class: $len(*characters)
        out_key: text_prop
optim:
  Optimizer:
    name: torch.optim.Adam
    args:
      lr: 0.0001
      betas: [ 0.9 ,0.999 ]
      weight_decay: 0.0005
  Scheduler:
    name: Warmup
    args:
      warm: 10000
loss:
  weight: [ 1.0 ]
  keys: [ [ text_prop ,[ text,lengths ] ] ]
  Loss:
    - name: CTCLossProxy
      args:
        zero_infinity: True
metric:
  weight: [ 1.0 ]
  keys: [ [ text_prop ,text ] ]
  Metric:
    - name: TextMetric
      args:
        decoder:
          - name: TextDecoder
            args:
              characters: *characters